backend/controllers/StokController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\TaStok;
use common\models\TaPemesanan;
use common\models\TaPemesananDetailSampai;
use backend\models\TaStokSearch;
use backend\models\TaPemesananSearch;
use backend\models\TaPemesananDetailSearch;
use backend\models\RefObatSearch;
use common\models\RefObat;
use common\models\TaPemesananDetail;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;

/**
 * StokController implements the CRUD actions for TaStok model.
 */
class StokController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulkdelete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all TaStok models.
     * @return mixed
     */
    public function actionIndex()
    {
        $request = Yii::$app->request;
        $searchModel = new TaStokSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Stok  ",
                'content' => $this->renderAjax('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                ]),
                'footer' => Html::button(Yii::t('kvgrid', 'Close'), ['class' => 'btn btn-light pull-left', 'data-dismiss' => "modal"])
            ];
        } else {
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
    }



    public function actionRiwayat($id = null)
    {
        $request = Yii::$app->request;
        $searchModel = new TaStokSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['id' => $id]);

        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Stok  ",
                'content' => $this->renderAjax('index_lihat', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                ]),
                'footer' => Html::button(Yii::t('kvgrid', 'Close'), ['class' => 'btn btn-light pull-left', 'data-dismiss' => "modal"])
            ];
        } else {
            return $this->render('index_lihat', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
    }


    public function actionProsesSelesai($id_pemesanan)
    {
        $request = Yii::$app->request;
        $modelPemesanan = TaPemesanan::find()->where(['id' => $id_pemesanan])->one();
        $modelPemesanan->setStatus(100);
        $modelPemesananDetail = TaPemesananDetail::find()->where(['id_pemesanan' => $id_pemesanan])->all();
        foreach ($modelPemesananDetail as $pemesananDetail) {
            $model = new TaStok();
            $model->id_obat = $pemesananDetail->id_obat;
            $model->id_status_stok = 1;
            $model->id_pemesanan = $id_pemesanan;
            $model->tanggal = date('Y-m-d');
            $model->jumlah = ($pemesananDetail->taPemesananDetailReturn) ? $pemesananDetail->jumlah - $pemesananDetail->taPemesananDetailReturn->jumlah : $pemesananDetail->jumlah;
            $model->setMasuk($pemesananDetail->id_obat, $model->jumlah);
            $model->save();
            $TaPemesananDetailSampai = new TaPemesananDetailSampai;
            $TaPemesananDetailSampai->id_pemesanan = $model->jumlah;
            $TaPemesananDetailSampai->id_obat = $model->id_obat;
            $TaPemesananDetailSampai->jumlah = $model->jumlah;
            $TaPemesananDetailSampai->save();
        }
        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose' => true, 'forceReload' => '#crud-datatable-pemesanan-pjax'];
        } else {
            return $this->redirect(['index']);
        }
    }


    /**
     * Displays a single TaStok model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $request = Yii::$app->request;
        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => Yii::t('kvgrid', 'View') . " Stok  ",
                'content' => $this->renderAjax('view', [
                    'model' => $this->findModel($id),
                ]),
                'footer' => Html::button(Yii::t('kvgrid', 'Close'), ['class' => 'btn btn-light pull-left', 'data-dismiss' => "modal"]) .
                    Html::a(Yii::t('kvgrid', 'Edit'), ['update', 'id' => $id], ['class' => 'btn btn-primary', 'role' => 'modal-remote'])
            ];
        } else {
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    public function actionPilihHilang()
    {
        $request = Yii::$app->request;
        $searchModel = new RefObatSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['not', ['stok' => null]]); //mencari nilai stok yang is not null
        //$dataProvider->query->andFilterWhere(['stok' => !null]);
        //->andWhere(['not', ['info' => null]]);

        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Pemesanan  ",
                'content' => $this->renderAjax('index_pilih_hilang', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                ]),
                'footer' => Html::button(Yii::t('kvgrid', 'Close'), ['class' => 'btn btn-light pull-left', 'data-dismiss' => "modal"])
            ];
        } else {
            return $this->render('index_pilih_hilang', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
    }
    public function actionPilihRusak()
    {
        $request = Yii::$app->request;
        $searchModel = new RefObatSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['not', ['stok' => null]]); //mencari nilai stok yang is not null
        //$dataProvider->query->andFilterWhere(['stok' => !null]);
        //->andWhere(['not', ['info' => null]]);

        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Pemesanan  ",
                'content' => $this->renderAjax('index_pilih_obat', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                ]),
                'footer' => Html::button(Yii::t('kvgrid', 'Close'), ['class' => 'btn btn-light pull-left', 'data-dismiss' => "modal"])
            ];
        } else {
            return $this->render('index_pilih_obat', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
    }


    public function actionHilang()
    {
        $request = Yii::$app->request;
        $searchModel = new TastokSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['id_status_stok' => 5]);
        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Pemesanan  ",
                'content' => $this->renderAjax('index_hilang', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                ]),
                'footer' => Html::button(Yii::t('kvgrid', 'Close'), ['class' => 'btn btn-light pull-left', 'data-dismiss' => "modal"])
            ];
        } else {
            return $this->render('index_hilang', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
    }
    public function actionPilihExpired()
    {
        $request = Yii::$app->request;
        $searchModel = new RefObatSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['not', ['stok' => null]]); //mencari nilai stok yang is not null
        //$dataProvider->query->andFilterWhere(['stok' => !null]);
        //->andWhere(['not', ['info' => null]]);

        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Pemesanan  ",
                'content' => $this->renderAjax('index_pilih_expired', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                ]),
                'footer' => Html::button(Yii::t('kvgrid', 'Close'), ['class' => 'btn btn-light pull-left', 'data-dismiss' => "modal"])
            ];
        } else {
            return $this->render('index_pilih_expired', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
    }
    public function actionRusak()
    {
        $request = Yii::$app->request;
        $searchModel = new TastokSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['id_status_stok' => 3]);

        if ($request->isAjax) {

backend/views/layouts/blank.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<main role="main">
    <div class="container">
        <?= $content ?>
    </div>
</main>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage();

backend/views/layouts/login.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\FontAsset;
use backend\assets\AppAsset;
use common\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\helpers\Url;


FontAsset::register($this);
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" style="--theme-deafult: #4831D4; --theme-secondary: #7366ff;" class="h-100">

<head>
  <meta charset="<?= Yii::$app->charset ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <?php $this->registerCsrfMetaTags() ?>
  <title><?= Html::encode($this->title) ?></title>
  <?php $this->head() ?>
</head>

<body class="dark-sidebar">
  <?php $this->beginBody() ?>
    <div class="container-fluid">
      <div class="row">
        <div class="col-xl-7"><?= Html::img('@web/images/login/2.jpg', ['class' => 'bg-img-cover bg-center',  'alt'=>"looginpage"]) ?></div>
        <div class="col-xl-5 p-0">
          <div class="login-card">
            <div>
              <div><a class="logo text-start" href="index.html"><?= Html::img('@web/images/logo/login.png', ['class' => 'img-fluid for-ligh',  'alt'=>"looginpage"]) ?></a></div>
              
              <div class="login-main"> 
                  <?= $content ?>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <?php $this->endBody() ?>
</body>

</html>
<?php $this->endPage();

backend/views/layouts/main copy.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use common\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;


AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">

<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <?php $this->head() ?>
</head>

<body class="d-flex flex-column h-100">
    <?php $this->beginBody() ?>

    <header>
        <?php
        NavBar::begin([
            'brandLabel' => Yii::$app->name,
            'brandUrl' => Yii::$app->homeUrl,
            'options' => [
                'class' => 'navbar navbar-expand-md navbar-dark bg-dark fixed-top',
            ],
        ]);
        $menuItems = [
            ['label' => 'Home', 'url' => ['/site/index']],
        ];
        if (Yii::$app->user->isGuest) {
            $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
        } else {
            $menuItems[] = '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'form-inline'])
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>';
        }
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav'],
            'items' => $menuItems,
        ]);
        NavBar::end();
        ?>
    </header>

    <main role="main" class="flex-shrink-0">
        <div class="container">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?= Alert::widget() ?>
            <?= $content ?>
        </div>
    </main>

    <footer class="footer mt-auto py-3 text-muted">
        <div class="container">
            <p class="float-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>
            <p class="float-right"><?= Yii::powered() ?></p>
        </div>
    </footer>

    <?php $this->endBody() ?>
</body>

</html>
<?php $this->endPage();

backend/views/layouts/menu.php
<?php

use yii\helpers\Url;
use yii\bootstrap4\Html;
?>

<ul class="sidebar-links" id="simple-bar">
    <li class="back-btn">
        <a href="<?= Url::home() ?>">
            <?= Html::img('@web/images/logo/logo-icon.png', ['class' => 'img-fluid']) ?>
        </a>
        <div class="mobile-back text-end"><span>Back</span><i class="fa fa-angle-right ps-2" aria-hidden="true"></i></div>
    </li>
    <li class="sidebar-main-title">
        <div>
            <h6 class="lan-1">Umum</h6>
            <!-- <p class="lan-2">Dashboards,widgets & layout.</p> -->
        </div>
    </li>
    <i class="icofont icofont-doctor-alt"></i>
    <li class="sidebar-list"><a class="sidebar-link sidebar-title link-nav" href="<?= Url::home() ?>"><i data-feather="airplay"> </i><span>Dashboard</span></a></li>
    <li class="sidebar-list"><a class="sidebar-link sidebar-title link-nav" href="<?= Url::toRoute('/obat') ?>"><i data-feather="list"> </i><span>Data Obat</span></a></li>
    <li class="sidebar-list"><a class="sidebar-link sidebar-title link-nav" href="<?= Url::toRoute('/obat-kategori') ?>"><i data-feather="list"> </i><span>Kategori Obat</span></a></li>
    <!-- <li class="sidebar-list"><a class="sidebar-link sidebar-title link-nav" href="<?= Url::toRoute('/pemesanan') ?>"><i data-feather="shopping-cart"> </i><span>Pemesanan</span></a></li> -->
    <li class="sidebar-list"><a class="sidebar-link sidebar-title link-nav" href="<?= Url::toRoute('/supplier') ?>"><i data-feather="list"> </i><span>Supplier</span></a></li>

    <li class="sidebar-list"><a class="sidebar-link sidebar-title" href="#"><i data-feather="sun"></i><span>Pemesanan</span></a>
        <ul class="sidebar-submenu">
            <li><a href="<?= Url::toRoute('pemesanan/index'); ?>">Pesan</a></li>
            <li><a href="<?= Url::toRoute('pemesanan/index-proses'); ?>">Proses</a></li>
            <li><a href="<?= Url::toRoute('pemesanan/index-sampai'); ?>">Sampai</a></li>
            <li><a href="<?= Url::toRoute('pemesanan/index-selesai'); ?>">Selesai</a></li>
        </ul>
    </li>
    <li class="sidebar-list"><a class="sidebar-link sidebar-title" href="#"><i data-feather="sun"></i><span>Penjualan</span></a>
        <ul class="sidebar-submenu">
            <li><a href="<?= Url::toRoute('penjualan/index'); ?>">Pesan</a></li>
            <li><a href="<?= Url::toRoute('penjualan/index-disiapkan'); ?>">Disiapkan</a></li>
            <li><a href="<?= Url::toRoute('penjualan/index-batal'); ?>">Batal</a></li>
            <li><a href="<?= Url::toRoute('penjualan/index-selesai'); ?>">Selesai</a></li>
        </ul> 
    </li>
    <li class="sidebar-list"><a class="sidebar-link sidebar-title" href="#"><i data-feather="sun"></i><span>return</span></a>
    <ul class="sidebar-submenu">
            <li><a href="<?= Url::toRoute('return/index'); ?>">Pesan</a></li>
            <li><a href="<?= Url::toRoute(['return/index','status'=>2]); ?>">Proses</a></li>
            <li><a href="<?= Url::toRoute(['return/index','status'=>3]); ?>">Sampai</a></li>
            <li><a href="<?= Url::toRoute(['return/index','status'=>100]); ?>">Selesai</a></li>
        </ul>
    </li>
    <li class="sidebar-list"><a class="sidebar-link sidebar-title" href="#"><i data-feather="sun"></i><span>Update Stok</span></a>
        <ul class="sidebar-submenu">
            <li><a href="<?= Url::toRoute('stok/rusak'); ?>">Rusak</a></li>
            <li><a href="<?= Url::toRoute('stok/expired'); ?>">Expired</a></li>
            <li><a href="<?= Url::toRoute('stok/hilang'); ?>">Hilang</a></li>
        </ul>
    </li>
   
    <!-- <li class="sidebar-list"><a class="sidebar-link sidebar-title link-nav" href="<?= Url::toRoute('pasien/home'); ?>"><i data-feather="airplay"> </i><span>Dashboard</span></a></li> -->

    <!-- <li class="sidebar-list"><a class="sidebar-link sidebar-title" href="#"><i data-feather="user"></i><span>Dokter</span></a>
        <ul class="sidebar-submenu">
            <li><a href="<?= Url::toRoute('dokter/create'); ?>">Input Data Dokter </a></li>
            <li><a href="<?= Url::toRoute('jadwal-dokter/dokter'); ?>">Jadwal Dokter</a></li>
            <li><a href="<?= Url::toRoute('dokter/index'); ?>">Data dokter</a></li>
        </ul>
    </li>
    <li class="sidebar-list"><a class="sidebar-link sidebar-title" href="#"><i data-feather="book-open"></i><span>Konsultasi</span></a>
        <ul class="sidebar-submenu">
            <li><a href="<?= Url::toRoute('pasien/konsultasi'); ?>">Input Data konsultasi </a></li>
           <li><a href="<?= Url::toRoute('jadwal-konsultasi/index'); ?>">Lihat konsultasi</a></li> -->
    <!-- <li><a href="<?= Url::toRoute('konsultasi/index'); ?>">Data konsultasi</a></li>
</ul>
</li>
<li class="sidebar-list"><a class="sidebar-link sidebar-title" href="#"><i data-feather="sun"></i><span>perawatan</span></a>
    <ul class="sidebar-submenu">
        <li><a href="<?= Url::toRoute('jenis-penanganan/create'); ?>">Input Data perawatan </a></li>
         <li><a href="<?= Url::toRoute('jadwal-perawatan/index'); ?>">Kategori perawatan</a></li> -->
    <!-- <li><a href="<?= Url::toRoute('jenis-penanganan/index'); ?>">Data perawatan</a></li>
    </ul>
</li>
<li class="sidebar-list"><a class="sidebar-link sidebar-title" href="#"><i data-feather="sun"></i><span>Referensi</span></a>
    <ul class="sidebar-submenu">
        <li><a href="<?= Url::toRoute('event/index'); ?>">Event </a></li>
        <li><a href="<?= Url::toRoute('diskon/index'); ?>">Diskon</a></li>
        <li><a href="<?= Url::toRoute('pasien-poin/pasien'); ?>">Poin</a></li>
    </ul>
</li>
<li class="sidebar-list"><a class="sidebar-link sidebar-title" href="#"><i data-feather="users"></i><span>Perawat</span></a>
    <ul class="sidebar-submenu">
        <li><a href="<?= Url::toRoute('perawat/create'); ?>">Input Data Perawat </a></li>
        <li><a href="<?= Url::toRoute('perawat/index'); ?>">Data Perawat</a></li>
    </ul>
</li>  -->
    <!-- <li class="sidebar-list"><a class="sidebar-link sidebar-title" href="#"><i data-feather="tag"></i><span>produk</span></a>
        <ul class="sidebar-submenu">
            <li><a href="<?= Url::toRoute('produk/create'); ?>">Input Data produk </a></li>
            <li><a href="<?= Url::toRoute('jadwal-produk/index'); ?>">Kategori produk</a></li>
            <li><a href="<?= Url::toRoute('produk/index'); ?>">Data produk</a></li>
        </ul>
    </li> -->
    <!-- <li class="sidebar-list"><a class="sidebar-link sidebar-title" href="#"><i class="icofont icofont-doctor-alt"></i><span>antrian</span></a>
        <ul class="sidebar-submenu">
            <li><a href="<?= Url::toRoute('antrian/create'); ?>">Input Data antrian </a></li>
            <li><a href="<?= Url::toRoute('jadwal-antrian/index'); ?>">Kategori antrian</a></li>
            <li><a href="<?= Url::toRoute('antrian/index'); ?>">Data antrian</a></li>
        </ul>
    </li> -->
    <!-- <li class="sidebar-list"><a class="sidebar-link sidebar-title" href="#"><i data-feather="airplay"></i><span class="lan-6">Widgets</span></a>
        <ul class="sidebar-submenu">
            <li><a href="general-widget.html">General</a></li>
            <li><a href="chart-widget.html">Chart</a></li>
        </ul>
    </li>
    <li class="sidebar-list"><a class="sidebar-link sidebar-title" href="#"><i data-feather="layout"></i><span class="lan-7">Page layout</span></a>
        <ul class="sidebar-submenu">
            <li><a href="box-layout.html">Boxed</a></li>
            <li><a href="layout-rtl.html">RTL</a></li>
            <li><a href="layout-dark.html">Dark Layout</a></li>
            <li><a href="hide-on-scroll.html">Hide Nav Scroll</a></li>
            <li><a href="footer-light.html">Footer Light</a></li>
            <li><a href="footer-dark.html">Footer Dark</a></li>
            <li><a href="footer-fixed.html">Footer Fixed</a></li>
        </ul>
    </li> -->
</ul>