backend/controllers/PenjualanController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\TaPenjualan;
use backend\models\TaPenjualanSearch as TaPenjualanSearch;
use backend\models\TaPenjualanDetailSearch;
use common\models\TaStok;
use common\models\RefObat;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;

/**
 * PenjualanController implements the CRUD actions for TaPenjualan model.
 */
class PenjualanController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulkdelete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all TaPenjualan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $request = Yii::$app->request;
        $searchModel = new TaPenjualanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['id_status' => 1]);

        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Penjualan  ",
                'content' => $this->renderAjax('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                ]),
                'footer' => Html::button(Yii::t('kvgrid', 'Close'), ['class' => 'btn btn-light pull-left', 'data-dismiss' => "modal"])
            ];
        } else {
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
    }

    public function actionIndexDisiapkan()
    {
        $request = Yii::$app->request;
        $searchModel = new TaPenjualanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['id_status' => 2]);


        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Penjualan  ",
                'content' => $this->renderAjax('index-disiapkan', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                ]),
                'footer' => Html::button(Yii::t('kvgrid', 'Close'), ['class' => 'btn btn-light pull-left', 'data-dismiss' => "modal"])
            ];
        } else {
            return $this->render('index-disiapkan', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
    }

    public function actionIndexBatal()
    {
        $request = Yii::$app->request;
        $searchModel = new TaPenjualanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['id_status' => 99]);

        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Penjualan  ",
                'content' => $this->renderAjax('index-batal', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                ]),
                'footer' => Html::button(Yii::t('kvgrid', 'Close'), ['class' => 'btn btn-light pull-left', 'data-dismiss' => "modal"])
            ];
        } else {
            return $this->render('index-batal', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
    }

    public function actionIndexSelesai()
    {
        $request = Yii::$app->request;
        $searchModel = new TaPenjualanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['id_status' => 100]);

        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Penjualan  ",
                'content' => $this->renderAjax('index-selesai', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                ]),
                'footer' => Html::button(Yii::t('kvgrid', 'Close'), ['class' => 'btn btn-light pull-left', 'data-dismiss' => "modal"])
            ];
        } else {
            return $this->render('index-selesai', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
    }

    public function actionSiapkan($id_penjualan)
    {
        $request = Yii::$app->request;
        $model = TaPenjualan::find()->where(['id' => $id_penjualan])->one();
        $model->setStatus(2);

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose' => true, 'forceReload' => '#crud-datatable-penjualan-pjax'];
        } else {
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }
    }

    public function actionBatalkan($id_penjualan)
    {
        $request = Yii::$app->request;
        $model = TaPenjualan::find()->where(['id' => $id_penjualan])->one();
        $penjDetailModels = TaPenjualanDetailSearch::findAll(['id_penjualan' => $id_penjualan]);

        $connection = \Yii::$app->db;
        $transaction = $connection->beginTransaction();

        try {
            foreach ($penjDetailModels as $penjDetail) {
                $obatModel = RefObat::findOne(['id' => $penjDetail->id_obat]);
                $obatModel->stok += $penjDetail->jumlah;
                $obatModel->save();
            }

            if ($model->save()) {
                $model->setStatus(99);
            }
            $transaction->commit();
        } catch (\Exception $e) {
            $transaction->rollBack();
            throw $e;
        } catch (\Throwable $e) {
            $transaction->rollBack();
            throw $e;
        }

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose' => true, 'forceReload' => '#crud-datatable-penjualan-pjax'];
        } else {
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }
    }

    public function actionSelesaikan($id_penjualan)
    {
        $request = Yii::$app->request;
        $model = TaPenjualan::find()->where(['id' => $id_penjualan])->one();
        $penDetailModels = TaPenjualanDetailSearch::findAll(['id_penjualan' => $id_penjualan]);


        /**
         * SEHARUSNYA STOK DI HAPUS DISINI
         * 
         */


        $connection = \Yii::$app->db;
        $transaction = $connection->beginTransaction();

        try {

            foreach ($penDetailModels as $penDetail) {
                $stokModel = new TaStok();
                $stokModel->id_status_stok = 2;
                $stokModel->id_obat = $penDetail->id_obat;
                $stokModel->id_pemesanan = $id_penjualan;
                $stokModel->jumlah = $penDetail->jumlah;
                $stokModel->tanggal = date('Y-m-d');
                $stokModel->save();
            }
            if ($model->save()) {
                $model->setStatus(100);
            }
            $transaction->commit();
        } catch (\Exception $e) {
            $transaction->rollBack();
            throw $e;
        } catch (\Throwable $e) {
            $transaction->rollBack();
            throw $e;
        }


        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose' => true, 'forceReload' => '#crud-datatable-penjualan-pjax'];
        } else {
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }
    }

    /**
     * Displays a single TaPenjualan model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $request = Yii::$app->request;
        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => Yii::t('kvgrid', 'View') . " Penjualan  ",
                'content' => $this->renderAjax('view', [
                    'model' => $this->findModel($id),
                ]),
                'footer' => Html::button(Yii::t('kvgrid', 'Close'), ['class' => 'btn btn-light pull-left', 'data-dismiss' => "modal"]) .
                    Html::a(Yii::t('kvgrid', 'Edit'), ['update', 'id' => $id], ['class' => 'btn btn-primary', 'role' => 'modal-remote'])
            ];
        } else {
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new TaPenjualan model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new TaPenjualan();
        $model->tanggal = date("Y-m-d");
        $model->no_invoice = "INV-" . date("Ymd") . "-" . random_int(0, 1000);
        $model->total_harga = 0;

        $connection = \Yii::$app->db;
        $transaction = $connection->beginTransaction();

        try {
            if ($model->save()) {

backend/views/penjualan/_columns.php
<?php

use backend\models\TaPenjualanSearch;
use backend\models\TaPenjualanDetailSearch;
use yii\helpers\Url;
use yii\helpers\Html;

return [
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
        // 'vAlign' => 'middle',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'no_invoice',
        'vAlign' => 'middle',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'tanggal',
        'vAlign' => 'middle',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'format' => 'currency',
        'attribute'=>'total_harga',
        'vAlign' => 'middle',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'statusPenjualan.status',
        'vAlign' => 'middle',
    ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'created_at',
        // 'vAlign' => 'middle',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'updated_at',
        // 'vAlign' => 'middle',
    // ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'header' => 'Aksi',
        'template' => '{detail}{proses}',
        'buttons' => [
            "detail" => function ($url, $model, $key) {
                return  Html::a('Detail', ['penjualan-detail/index', 'id_penjualan' => $model->id], [
                    'class' => 'btn btn-primary mb-2',
                    'title'=>Yii::t('kvgrid','Daftar/Pilih Obat'), 
                    //'data-pjax' => '0',
                    'role' => 'modal-remote',
                    'target' => 'modal'
                ]);
            },
            "proses" => function ($url, $model, $key) {
                $jumlahPesanan = TaPenjualanDetailSearch::find()->where(['id_penjualan' => $model->id])->count() ;
                $status = ($jumlahPesanan < 1) ? 'disabled' : '';
                return  Html::a('Siapkan', ['penjualan/siapkan', 'id_penjualan' => $model->id], [
                        'class' => "btn btn-success mb-2 {$status}",
                        'title'=>Yii::t('kvgrid','Siapkan'), 
                        'role'=>'modal-remote',
                        'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                        'data-request-method'=>'post',
                        'data-toggle'=>'tooltip',
                        'data-confirm-title'=>Yii::t('kvgrid','Are you sure?'),
                        'data-confirm-message'=>Yii::t('kvgrid','Apakah anda yakin akan menyiapkan pesanan ini ?')]);
            },
        ],
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'template' => '{delete}',
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'viewOptions'=>['role'=>'modal-remote','title'=>Yii::t('kvgrid','View'),'data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>Yii::t('kvgrid','Update'), 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>Yii::t('kvgrid','Delete'), 
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title'=>Yii::t('kvgrid','Are you sure?'),
                          'data-confirm-message'=>Yii::t('kvgrid','Are you sure want to delete this item?')], 
    ],
  

];   

backend/views/penjualan/_columns_batal.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

return [
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
        // 'vAlign' => 'middle',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'no_invoice',
        'vAlign' => 'middle',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'tanggal',
        'vAlign' => 'middle',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'format' => 'currency',
        'attribute'=>'total_harga',
        'vAlign' => 'middle',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'statusPenjualan.status',
        'vAlign' => 'middle',
    ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'created_at',
        // 'vAlign' => 'middle',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'updated_at',
        // 'vAlign' => 'middle',
    // ],
    // [
    //     'class' => 'kartik\grid\ActionColumn',
    //     'dropdown' => false,
    //     'template'=>'{view}{delete}',
    //     'vAlign'=>'middle',
    //     'urlCreator' => function($action, $model, $key, $index) { 
    //             return Url::to([$action,'id'=>$key]);
    //     },
    //     'viewOptions'=>['role'=>'modal-remote','title'=>Yii::t('kvgrid','View'),'data-toggle'=>'tooltip'],
    //     'updateOptions'=>['role'=>'modal-remote','title'=>Yii::t('kvgrid','Update'), 'data-toggle'=>'tooltip'],
    //     'deleteOptions'=>['role'=>'modal-remote','title'=>Yii::t('kvgrid','Delete'), 
    //                       'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
    //                       'data-request-method'=>'post',
    //                       'data-toggle'=>'tooltip',
    //                       'data-confirm-title'=>Yii::t('kvgrid','Are you sure?'),
    //                       'data-confirm-message'=>Yii::t('kvgrid','Are you sure want to delete this item?')], 
    // ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'header' => 'Aksi',
        'template' => '{detail}',
        'buttons' => [
            "detail" => function ($url, $model, $key) {
                return  Html::a('Detail', ['penjualan-detail/index-detail', 'id_penjualan' => $model->id], [
                    'class' => 'btn btn-primary mb-2',
                    'title'=>Yii::t('kvgrid','Detail Penjualan'), 
                    //'data-pjax' => '0',
                    'role' => 'modal-remote',
                    'target' => 'modal'
                ]);
            // },
            // "proses" => function ($url, $model, $key) {
            //     return  Html::a('Siapkan', ['penjualan/index-disiapkan'], [
            //         'class' => 'btn btn-success mb-2',
            //         //'data-pjax' => '0',
            //         'role' => 'modal-remote',
            //         'target' => 'modal'
            //     ]);
            // },
            }
        ],
    ],

];   

backend/views/penjualan/_columns_disiapkan.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

return [
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
        // 'vAlign' => 'middle',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'no_invoice',
        'vAlign' => 'middle',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'tanggal',
        'vAlign' => 'middle',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'format' => 'currency',
        'attribute'=>'total_harga',
        'vAlign' => 'middle',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'statusPenjualan.status',
        'vAlign' => 'middle',
    ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'created_at',
        // 'vAlign' => 'middle',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'updated_at',
        // 'vAlign' => 'middle',
    // ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'header' => 'Aksi',
        'template' => '{detail}',
        'buttons' => [
            "detail" => function ($url, $model, $key) {
                return  Html::a('Detail', ['penjualan-detail/index-detail', 'id_penjualan' => $model->id], [
                    'class' => 'btn btn-primary mb-2',
                    'title'=>Yii::t('kvgrid','Detail Penjualan'), 
                    //'data-pjax' => '0',
                    'role' => 'modal-remote',
                    'target' => 'modal'
                ]);
            },
        ],
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'header' => 'Aksi',
        'template' => '{batal}{selesai}',
        'buttons' => [
            "batal" => function ($url, $model, $key) {
                return  Html::a('Batalkan', ['penjualan/batalkan', 'id_penjualan' => $model->id], [
                        'class' => "btn btn-success mb-2",
                        'role'=>'modal-remote',
                        'title'=>Yii::t('kvgrid','Batalkan'), 
                        'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                        'data-request-method'=>'post',
                        'data-toggle'=>'tooltip',
                        'data-confirm-title'=>Yii::t('kvgrid','Are you sure?'),
                        'data-confirm-message'=>Yii::t('kvgrid','Apakah anda yakin akan membatalkan penjualan ini ?')]);
            },
            "selesai" => function ($url, $model, $key) {
                return  Html::a('Selesai', ['penjualan/selesaikan', 'id_penjualan' => $model->id], [
                        'class' => "btn btn-danger mb-2",
                        'role'=>'modal-remote',
                        'title'=>Yii::t('kvgrid','Selesaikan'), 
                        'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                        'data-request-method'=>'post',
                        'data-toggle'=>'tooltip',
                        'data-confirm-title'=>Yii::t('kvgrid','Are you sure?'),
                        'data-confirm-message'=>Yii::t('kvgrid','Apakah anda yakin akan menyelesaikan penjualan ini ?')]);
            },
        ],
    ],
    // [
    //     'class' => 'kartik\grid\ActionColumn',
    //     'dropdown' => false,
    //     'template' => '{delete}',
    //     'vAlign'=>'middle',
    //     'urlCreator' => function($action, $model, $key, $index) { 
    //             return Url::to([$action,'id'=>$key]);
    //     },
    //     'viewOptions'=>['role'=>'modal-remote','title'=>Yii::t('kvgrid','View'),'data-toggle'=>'tooltip'],
    //     'updateOptions'=>['role'=>'modal-remote','title'=>Yii::t('kvgrid','Update'), 'data-toggle'=>'tooltip'],
    //     'deleteOptions'=>['role'=>'modal-remote','title'=>Yii::t('kvgrid','Delete'), 
    //                       'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
    //                       'data-request-method'=>'post',
    //                       'data-toggle'=>'tooltip',
    //                       'data-confirm-title'=>Yii::t('kvgrid','Are you sure?'),
    //                       'data-confirm-message'=>Yii::t('kvgrid','Are you sure want to delete this item?')], 
    // ],
  

];   

backend/views/penjualan/_columns_selesai.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

return [
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
        // 'vAlign' => 'middle',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'no_invoice',
        'vAlign' => 'middle',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'tanggal',
        'vAlign' => 'middle',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'format' => 'currency',
        'attribute'=>'total_harga',
        'vAlign' => 'middle',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'statusPenjualan.status',
        'vAlign' => 'middle',
    ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'created_at',
        // 'vAlign' => 'middle',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'updated_at',
        // 'vAlign' => 'middle',
    // ],

        [
        'class' => 'kartik\grid\ActionColumn',
        'header' => 'Aksi',
        'template' => '{detail}',
        'buttons' => [
            "detail" => function ($url, $model, $key) {
                return  Html::a('Detail', ['penjualan-detail/index-detail', 'id_penjualan' => $model->id], [
                    'class' => 'btn btn-primary mb-2',
                    'title'=>Yii::t('kvgrid','Detail Penjualan'), 
                    //'data-pjax' => '0',
                    'role' => 'modal-remote',
                    'target' => 'modal'
                ]);
            },
            // "proses" => function ($url, $model, $key) {
            //     return  Html::a('Siapkan', ['penjualan/index-disiapkan'], [
            //         'class' => 'btn btn-success mb-2',
            //         //'data-pjax' => '0',
            //         'role' => 'modal-remote',
            //         'target' => 'modal'
            //     ]);
            // },
        ],
    ],
    // [
    //     'class' => 'kartik\grid\ActionColumn',
    //     'dropdown' => false,
    //     'template' => '{delete}',
    //     'vAlign'=>'middle',
    //     'urlCreator' => function($action, $model, $key, $index) { 
    //             return Url::to([$action,'id'=>$key]);
    //     },
    //     'viewOptions'=>['role'=>'modal-remote','title'=>Yii::t('kvgrid','View'),'data-toggle'=>'tooltip'],
    //     'updateOptions'=>['role'=>'modal-remote','title'=>Yii::t('kvgrid','Update'), 'data-toggle'=>'tooltip'],
    //     'deleteOptions'=>['role'=>'modal-remote','title'=>Yii::t('kvgrid','Delete'), 
    //                       'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
    //                       'data-request-method'=>'post',
    //                       'data-toggle'=>'tooltip',
    //                       'data-confirm-title'=>Yii::t('kvgrid','Are you sure?'),
    //                       'data-confirm-message'=>Yii::t('kvgrid','Are you sure want to delete this item?')], 
    // ],
];   

backend/views/penjualan/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\TaPenjualan */
/* @var $form yii\widgets\ActiveForm */
?>

<?php if (!Yii::$app->request->isAjax){ ?>
<div class="row">
<div class="col-sm-12">
<div class="card">
<div class="card-body">
<?php } ?>

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'no_invoice')->textInput(['maxlength' => true]) ?>

    <?php //$form->field($model, 'tanggal')->textInput() ?>

    <?php //$form->field($model, 'total_harga')->textInput() ?>

    <?php //$form->field($model, 'id_status')->textInput() ?>

    <?php //$form->field($model, 'created_at')->textInput() ?>

    <?php //$form->field($model, 'updated_at')->textInput() ?>

  
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Menambahkan' : 'Ubah', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    

<?php if (!Yii::$app->request->isAjax){ ?>
</div>
</div>
</div>
</div>
<?php } ?>

backend/views/penjualan/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\TaPenjualan */

$this->title = Yii::t('kvgrid','Add').' Penjualan ';
$this->params['breadcrumbs'][] = ['label' => 'Data', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="ta-penjualan-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

backend/views/penjualan/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\TaPenjualan */

$this->title = Yii::t('kvgrid','Update').' Penjualan ';
$this->params['breadcrumbs'][] = ['label' => 'Data', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="ta-penjualan-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/penjualan/view.php
<?php

use yii\widgets\DetailView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\TaPenjualan */
?>
<?php if (!Yii::$app->request->isAjax){ ?>
<div class="row">
<div class="col-sm-12">
<div class="card">
<div class="card-header">
    <?= Html::a(Yii::t('kvgrid','Back To Tabel'),['index'],['class'=>'btn btn-primary'])?>
</div>
<div class="card-body">
<?php } ?>
 
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'no_invoice',
            'tanggal',
            'total_harga',
            'id_status',
            'created_at',
            'updated_at',
        ],
    ]) ?>

<?php if (!Yii::$app->request->isAjax){ ?>
</div>
</div>
</div>
</div>
<?php } ?>